stages:
  - build

.build:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_HOST: docker:2375
  before_script:
  script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
    - export TAG=$( if [[ ! -z "$DOCKER_REGISTRY" ]]; then echo "$DOCKER_REGISTRY/"; fi )mvochoa/blog:$CI_COMMIT_TAG
    - docker build -t $TAG .
    - docker push $TAG

build::image:
  extends: .build
  before_script:
    - export CI_COMMIT_TAG=latest
  only:
    - main

build::image::tag:
  extends: .build
  before_script:
    - echo "Ok"
  only:
    - tags
