version: "3.5"
services:
    app:
        image: node:16-alpine
        working_dir: /var/app
        volumes:
            - ./:/var/app
            - node_modules:/var/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        command: sh -c 'yarn && yarn run dev'

volumes:
    node_modules: